- shell++:
    - - sudo dpkg --configure -a
      - Fix for dpkg was interrupted on Ubuntu 18.04

- aptget:
    neovim:
      ppa_source: 'ppa:neovim-ppa/stable'
    git:
      ppa_source: 'ppa:git-core/ppa'
    fasd:
      ppa_source: 'ppa:aacebedo/fasd'
    hstr:
      ppa_source: 'ppa:ultradvorka/ppa'
    # python3: # Python 3.9+
    #   ppa_source: 'ppa:deadsnakes/ppa'
# - aptget:
#     fish:
#       ppa_source: 'ppa:c/release-2'
- aptget:
    - zsh
    - lnav
    - tmux
    - source-highlight
    - editorconfig
    - fortune-mod
    - apg
    - jq
    - ccze
    - ncdu
- aptget:
    - python-pip
    - python3-pip
    - ruby
# Python and Ruby build requirements, see https://github.com/pyenv/pyenv/wiki/Common-build-problems
- aptget:
    - wget curl make llvm build-essential xz-utils libffi-dev liblzma-dev
    - python-openssl # Not found on Ubuntu 18.04+
- aptget:
    - >-
      libssl-dev zlib1g-dev libbz2-dev libreadline-dev
      libsqlite3-dev libncurses5-dev libncursesw5-dev tk-dev
