- shell++:
    - - sudo dpkg --configure -a
      - Fix for dpkg was interrupted on Ubuntu 18.04
    - - sudo locale-gen "en_US.UTF-8"
      - Fix locale issues on Ubuntu 22.04, see https://askubuntu.com/questions/162391/how-do-i-fix-my-locale-issue

- aptget:
    # Python and Ruby build requirements, see https://github.com/pyenv/pyenv/wiki/Common-build-problems
    - curl make llvm build-essential xz-utils libffi-dev liblzma-dev
    - lnav
    - fortune-mod
    - apg
    - ccze
    - python3-pip
    - ruby
    - python3-openssl
    - software-properties-common # For install PPA, see https://askubuntu.com/questions/422975/e-package-python-software-properties-has-no-installation-candidate

- aptget:
    - >-
      zlib1g-dev libbz2-dev
    - libsqlite3-dev
    - libssl-dev
    - libreadline-dev
    - libncurses5-dev libncursesw5-dev
    - tk-dev # Hang on install on Ubuntu 22.04 because of tzdata timezone select diaglog

    # This fix `curl: (60) server certificate verification failed. CAfile: /etc/ssl/certs/ca-certificates.crt CRLfile: none` when use `brew install` on Ubuntu 16.04
    # See https://www.zoocha.com/news/fixing-issues-multiple-servers-caused-recently-expired-root-certificate
    - libgnutls-openssl27

- aptget:

    # Need for `az login` interactive
    wslu:
      ppa_source: 'ppa:wslutilities/wslu'
