- shell++:
    - - sudo dpkg --configure -a
      - Fix for dpkg was interrupted on Ubuntu 18.04
    - - sudo locale-gen "en_US.UTF-8"
      - Fix locale issues on Ubuntu 22.04, see https://askubuntu.com/questions/162391/how-do-i-fix-my-locale-issue

# - aptget:
    # Obsoleted by Homebrew
    # neovim:
    #   ppa_source: 'ppa:neovim-ppa/stable'
    # git:
    #   ppa_source: 'ppa:git-core/ppa'
    # Obsoleted by Homebrew, use zoxide from zinit instead
    # fasd:
    #   ppa_source: 'ppa:aacebedo/fasd'
    # Obsoleted by Homebrew, use fzf instead
    # hstr:
    #   ppa_source: 'ppa:ultradvorka/ppa'
    # deadsnakes: # Python 3.9+
    #   ppa_source: 'ppa:deadsnakes/ppa'
# - aptget:
#     fish:
#       ppa_source: 'ppa:c/release-2'
- aptget:
    - lnav
    - fortune-mod
    - apg
    - ccze
    - python3-pip
    - ruby
    # Python and Ruby build requirements, see https://github.com/pyenv/pyenv/wiki/Common-build-problems
    - curl make llvm build-essential xz-utils libffi-dev liblzma-dev
    - python3-openssl
- aptget:
    - >-
      libssl-dev zlib1g-dev libbz2-dev libreadline-dev
      libsqlite3-dev libncurses5-dev libncursesw5-dev tk-dev

    # This fix `curl: (60) server certificate verification failed. CAfile: /etc/ssl/certs/ca-certificates.crt CRLfile: none` when use `brew install` on Ubuntu 16.04
    # See https://www.zoocha.com/news/fixing-issues-multiple-servers-caused-recently-expired-root-certificate
    - libgnutls-openssl27

