- defaults:
    link:
      create: true
      relink: true
      force: true

# See https://nixos-and-flakes.thiscute.world/nixos-with-flakes/start-using-home-manager
- brew:
    - lsd # Replace `exa` (Error: exa has been disabled because it is not maintained upstream!)
    - fzf
    - todo-txt
    - gcc
    - fastfetch
    - editorconfig
    - jq
    - ncdu
    - htop
    - btop # In case htop don't work
    - direnv
    - screen # 5.0 to support True Color
    - byobu # screen + tmux
    - duf # a better 'df' alternative, see https://freedium.cfd/https://blog.devops.dev/6-linux-utilities-you-should-install-right-now-75470963a021
    - sponge # like `tee` but soak up standard input before write to a file

- link:
    ~/.screenrc: apps/screen/screenrc
