- defaults:
    link:
      create: true
      relink: true
      force: true

# See https://nixos-and-flakes.thiscute.world/nixos-with-flakes/start-using-home-manager
- brew:
    - lsd # Replace `exa` (Error: exa has been disabled because it is not maintained upstream!)
    - fzf
    - todo-txt
    - gcc
    - fastfetch
    - editorconfig
    - jq
    - ncdu
    - htop
    - btop # In case htop don't work
    - direnv
    - screen # 5.0 to support True Color
    - byobu # screen + tmux

- link:
    ~/.screenrc: apps/screen/screenrc
