- defaults:
    link:
      create: true
      relink: true
      force: true

# Install common dependencies
- brew:
    - ca-certificates
    - glibc
    - gcc
    - make      # Require for ble.sh and ruby-build
    - wget
    # Require libs for pyenv doctor -v
    - readline
    - sqlite
    # Update to latest openssl for python-pyenv-doctor
    # - openssl@1.1

# See https://nixos-and-flakes.thiscute.world/nixos-with-flakes/start-using-home-manager
- brew:
    - lsof      # list open files, requires for Zinit's plugin caarlos0/ports
    - fzf
    - fastfetch
    - ncdu
    - htop
    - btop      # In case htop don't work
    - screen    # 5.0 to support True Color
    - byobu     # screen + tmux
    - duf       # a better 'df' alternative, see https://freedium.cfd/https://blog.devops.dev/6-linux-utilities-you-should-install-right-now-75470963a021
    - sponge    # like `tee` but soak up standard input before write to a file
    - fd        # Simple, fast and user-friendly alternative to find
    # Favorite tools, see https://blog.dalanmiller.com/my-favorite-command-line-tools/
    - bat       # Clone of `cat` with syntax highlighting and Git integration
    - dua-cli   # View disk space usage and delete unwanted data, fast
    - hwatch    # Modern alternative to the watch command
    - hyperfine # Command-line benchmarking tool
    - mtr       # 'traceroute' and 'ping' in a single tool
    - xsv       # Fast CSV toolkit written in Rust
    - jq
    - git

- link:
    ~/.screenrc: apps/screen/screenrc

# - shell++:
#   - description: Include Hombrew PATH for all users (cause permission issue when install softwares using root)
#     condition: '[ ! -f /etc/profile.d/homebrewpath.sh ]'
#   - stderr: true
#     command: |

#       BREW_PREFIX=$(brew --prefix)
#       sudo tee /etc/profile.d/homebrewpath.sh > /dev/null <<EOF
#       if ! echo \${PATH} | /bin/grep -q ${BREW_PREFIX}/bin ; then
#         PATH=${BREW_PREFIX}/bin:\${PATH}
#       fi
#       if ! echo \${PATH} | /bin/grep -q ${BREW_PREFIX}/sbin ; then
#         if [ \`/usr/bin/id -u\` = 0 ] ; then
#           PATH=${BREW_PREFIX}/sbin:\${PATH}
#         fi
#       fi
#       EOF

#       sudo chmod +x /etc/profile.d/homebrewpath.sh
