- defaults:
    link:
      create: true
      relink: true
      force: true

- brew:
  - fastlane
  - imagemagick  # Required for fastlane badge
  - librsvg  # Required for fastlane badge, see https://github.com/fastlane/fastlane/issues/8598

- shell++:
  - description: Uninstall fastlane gem to force use brew's fastlane
    condition: 'true'
  - stdout: true
    stderr: true
    command: 'rbenv exec gem uninstall fastlane --all --executables || true'
