- defaults:
    link:
      create: true
      relink: true
      force: true
# Obsoleted by mise
# - link:
#     ~/.go-version: development/go/go-version
#     ~/.config/zsh/settings/go.zsh: development/go/zsh/settings/go.zsh
