- defaults:
    link:
      create: true
      relink: true
      force: true
- link:
    ~/.Brewfile: Brewfile

- shell++:
  - description: Install Homebrew
    condition: '! hash brew 2>/dev/null'
  - stdout: true
    stderr: true
    command: |
      # Ask for the administrator password upfront
      sudo -v

      # Keep-alive: update existing `sudo` time stamp until `.macos` has finished
      while true; do sudo -n true; sleep 60; kill -0 "$$" || exit; done 2>/dev/null &

      /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

- brewfile:
    file: Brewfile

- tap:
  - caskroom/versions
  - caskroom/cask
  # - pivotal/tap

- brew:
  - mas
  - git-extras
  - git-flow-avh
  - gitversion
  - exa
  # - fish
  - tmux
  - tmate
  # - curl --with-openssl
  - curl

- brew: [zsh, zsh-completions, zsh-syntax-highlighting]

- cask:
  - dotnet
  - gitkraken
  - iterm2
  - kdiff3
  - visual-studio
  - visual-studio-code

- shell++:
  - description: Install Apps
    condition: 'hash brew 2>/dev/null'
  - stdout: true
    stderr: true
    command: |
      # Ask for the administrator password upfront
      sudo -v

      # Keep-alive: update existing `sudo` time stamp until `.macos` has finished
      while true; do sudo -n true; sleep 60; kill -0 "$$" || exit; done 2>/dev/null &

      # Install XCode
      mas install 497799835
      sudo xcodebuild -license accept
      xcode-select --install

      # Install Slack
      mas install 803453959

      # Install OneDrive
      mas install 823766827
