- defaults:
    link:
      create: true
      relink: true
      force: true
- link:
    ~/.Brewfile: Brewfile

# Installed outside of dotbot because it's required by git.
# - shell++:
#   - description: Install Xcode command line tools
#     condition: 'true'
#   - stdout: true
#     stderr: true
#     command: |
#       # Install Xcode command line tools
#       xcode-select --install

- shell++:
  - description: Install Homebrew
    condition: '! hash brew 2>/dev/null'
  - stdout: true
    stderr: true
    command: |
      /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

# - brewfile:
#     # This accepts the same options as `brew bundle` command:
#     file: ~/.Brewfile
#     no-upgrade: true

# Deprecated by default homebrew install
# - tap:
#   - homebrew/cask-versions
#   - homebrew/cask
#   - pivotal/tap

- brew:
  # For git-restore-mtime (replace git-settimes.pl)
  - git-tools
  - git-credential-manager # Require for Apple Silicon, see https://github.com/git-ecosystem/git-credential-manager/issues/574
  - mas
  - git-extras
  # - git-flow-avh
  # - fish
  - tmate
  # - curl --with-openssl
  - wget
  - curl
  - gawk
  # Update 12 year old rsync on macOS Mojave
  - rsync
  # Required by dotnet
  # - mono-libgdiplus
  # - gitversion

# Support for dedupe.sh, see https://apple.stackexchange.com/questions/69223/how-to-replace-mac-os-x-utilities-with-gnu-core-utilities
# - brew:
#   - coreutils
#   - findutils
#   - gnu-tar
#   - gnu-sed
#   - gawk
#   - gnutls
#   - gnu-indent
#   - grep
#   - gnu-cp
#   - jdupes

- brew:
  # - zsh # arm64 on Apple Silicon
  - zsh-completions
  - zsh-syntax-highlighting

- cask:
  - powershell
  - iterm2
  - visual-studio-code
  - gitkraken
  # Obsoleted, use official install scripts instead
  # - dotnet
  # - kdiff3 # not available any more
  # - visual-studio # Will install with Unity

# - shell++:
#   - description: Install dotnet
#     condition: 'true'
#   - stdout: true
#     stderr: true
#     command: |
#       brew install cask dotnet

# - shell++:
#   - description: Install GitVersion 5.0.1
#     condition: 'true'
#   - stdout: true
#     stderr: true
#     command: |
#       # 5.0.1 is latest stable version that support exit code.
#       BREW_GITVERSION=5.0.1
#       brew unlink gitversion &
#       # brew cleanup -s gitversion && brew cleanup --prune-prefix

#       # See https://stackoverflow.com/questions/3987683/homebrew-install-specific-version-of-formula/55764594#comment102767816_53766019
#       # Use --no-git to avoid `brew update` error
#       brew tap-new --no-git $USER/local-tap
#       # extract with a version seems to run a `git log --grep` under the hood
#       brew extract --force --version=${BREW_GITVERSION} gitversion $USER/local-tap

#       # !BUG: fix `Calling bottle :unneeded is disabled!`
#       sed -i -E 's/ \(bottle\)/ #\1/g' /usr/local/Homebrew/Library/Taps/${USER}/homebrew-local-tap/Formula/gitversion@${BREW_GITVERSION}.rb
#       # Install your new version from the tap
#       brew install gitversion@${BREW_GITVERSION}
#       # Note this "fails" trying to grab a bottle for the package and seems to have
#       # some odd doubling of the version in that output, but this isn't fatal.

#       ## Obsoleted
#       # brew unlink gitversion & brew install https://raw.githubusercontent.com/Homebrew/homebrew-core/56b5ff6813815eec8f8bbbe92856c1ce827ececc/Formula/gitversion.rb

#       brew link gitversion@${BREW_GITVERSION}
#       brew pin gitversion@${BREW_GITVERSION}

#       # Update the formulae and Homebrew itself
#       brew update

#       # Upgrade everything
#       brew upgrade

- shell++:
  - description: Install Apps
    condition: 'true'
  - stdout: true
    stderr: true
    command: |
      # Install XCode
      mas install 497799835
      sudo xcodebuild -license accept

      # Install Slack
      mas install 803453959

      # Install OneDrive
      mas install 823766827
