- defaults:
    link:
      create: true
      relink: true
      force: true
- link:
    ~/.Brewfile: Brewfile

- shell++:
  - description: Install Homebrew
    condition: '! hash brew 2>/dev/null'
  - stdout: true
    stderr: true
    command: |
      /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

- brewfile:
    # This accepts the same options as `brew bundle` command:
    file: ~/.Brewfile

- tap:
  - homebrew/cask-versions
  - homebrew/cask
  # - pivotal/tap

- brew:
  - mas
  - git-extras
  - git-flow-avh
  # - gitversion
  - exa
  # - fish
  - tmux
  - tmate
  # - curl --with-openssl
  - wget
  - curl
  # Update 12 year old rsync on macOS Mojave
  - rsync

- brew: [zsh, zsh-completions, zsh-syntax-highlighting]

- cask:
  - dotnet
  - gitkraken
  - iterm2
  # - kdiff3 # not available any more
  # - visual-studio # Will install with Unity
  - visual-studio-code

- shell++:
  - description: Install GitVersion 5.0.1
    condition: 'true'
  - stdout: true
    stderr: true
    command: |
      # 5.0.1 is latest stable version that support exit code.
      brew unlink gitversion & brew install https://raw.githubusercontent.com/Homebrew/homebrew-core/56b5ff6813815eec8f8bbbe92856c1ce827ececc/Formula/gitversion.rb

- shell++:
  - description: Install Apps
    condition: 'true'
  - stdout: true
    stderr: true
    command: |
      # Install XCode
      mas install 497799835
      sudo xcodebuild -license accept

      # Install Slack
      mas install 803453959

      # Install OneDrive
      mas install 823766827

- shell++:
  - description: Run XCode First Lauch to accept license
    condition: '! xcodebuild -checkFirstLaunchStatus'
  - stdout: true
    stderr: true
    command: |
      sudo xcodebuild -runFirstLaunch

      # Install Xcode command line tools
      xcode-select --install
