- defaults:
    link:
      create: true
      relink: true
      force: true
- shell++:
    - description: Install galenguyer/nano-syntax-highlighting
      condition: 'true'
    - stdout: true
      stderr: true
      command: >
        if [ -d ~/.nano/.git ]; then
          cd ~/.nano
          git pull
        else
          git clone https://github.com/galenguyer/nano-syntax-highlighting.git ~/.nano
        fi
- link:
    ~/.config/nano/nanorc: editors/nano/nanorc
