- shell++:
  - description: Setting OSX defaults
    condition: 'true'
  - stdout: true
    stdin: true
    stderr: true
    command: |
      sudo cp -f ~/.dotfiles/apps/misc/macos/Library/LaunchAgents/com.luomat.loginhook.plist /Library/LaunchAgents/

      # iTerm 2 Shell integration
      curl -L https://iterm2.com/misc/install_shell_integration.sh | bash

      . ~/.dotfiles/apps/misc/macos/settings
