- defaults:
    link:
      create: true
      relink: true
      force: true
- link:
    ~/.config/common/init_functions.sh: shells/common/init_functions.sh

# !NOTE: /etc/profile.d does not exist on macOS
# - shell++:
#   - description: Inject init scripts for all users' Login Shell
#     condition: 'true'
#   - stdout: true
#     stderr: true
#     command: |
#       sudo cp -L ~/.config/common/init_functions.sh /etc/profile.d/00-dotfiles-init-functions.sh
