- defaults:
    link:
      create: true
      relink: true
      force: true
- link:
    ~/.config/starship.toml: shells/plugins/starship/starship.xshell.toml

- brew:
    - starship

# - shell++:
#   - description: Installing Starship
#     condition: 'true'
#   - stdout: true
#     stderr: true
#     command: |
#       # Install Starship as default for all users, see https://starship.rs/
#       curl -sS https://starship.rs/install.sh | sudo sh -s -- -y
