- defaults:
    link:
      create: true
      relink: true
      force: true
- shell++:
    - description: Install tmuxinator
      stdout: true
      stderr: true
      command: gem install tmuxinator
    - description: Install tmuxifier
      stdout: true
      stderr: true
      command: |
        if [ -d ~/.tmuxifier ]; then
          # Cannot use pushd since this is /bin/sh shell
          cd ~/.tmuxifier
          git pull
          cd -
        else
          git clone https://github.com/jimeh/tmuxifier.git ~/.tmuxifier
        fi
- link:
    ~/.local/bin/battery.sh: apps/tmux/bin/battery.sh
    ~/.local/bin/tmux-mem-cpu-load: apps/tmux/bin/tmux-mem-cpu-load
    ~/.tmux.conf: apps/tmux/tmux.conf
    ~/.tmux/solarized: apps/tmux/tmux/solarized
    ~/.config/zsh/settings/tmuxifier.zsh: apps/tmux/tmuxifier/zsh/settings/tmuxifier.zsh
