- defaults:
    link:
      create: true
      relink: true
      force: true
- clean:
    - ~/.vim
- link:
    ~/.vim/UltiSnips: editors/vim/vim/UltiSnips
    ~/.vim/autoload/plug.vim: editors/vim/vim/autoload/plug.vim
    ~/.vim/ftplugin/fish.vim: editors/vim/vim/ftplugin/fish.vim
    ~/.vim/ftdetect/xaml.vim: editors/vim/vim/ftdetect/xaml.vim
    ~/.vim/insert_matching_spaces.vim: editors/vim/vim/insert_matching_spaces.vim
    ~/.vim/map_line_block_mover_keys.vim: editors/vim/vim/map_line_block_mover_keys.vim
    ~/.vim/map_highlighting_keys.vim: editors/vim/vim/map_highlighting_keys.vim
    ~/.vim/mkzip.sh: editors/vim/vim/mkzip.sh
    ~/.vim/run-last.vim: editors/vim/vim/run-last.vim
    ~/.vim/set_abbreviations.vim: editors/vim/vim/set_abbreviations.vim
    ~/.vim/toggle_highlights.vim: editors/vim/vim/toggle_highlights.vim
    ~/.vim/update_visual_highlight_color.vim: editors/vim/vim/update_visual_highlight_color.vim
    ~/.vim/vim-fireplace-mappings.vim: editors/vim/vim/vim-fireplace-mappings.vim
    ~/.vimrc: editors/vim/vimrc
    ~/.gvimrc: editors/vim/gvimrc
    ~/.config/nvim/init.vim: editors/vim/config/nvim/init.linux.vim
    ~/.vim/plugins.vim: editors/vim/plugins/plugins_linux.vim
    ~/.vim/plugins_shared.vim: editors/vim/plugins/plugins_shared.vim
- brew:
    - neovim
- shell++:
    # - - pip2 install neovim
    #   - Installing Python 2 NeoVim plugin
    # - - pip3 install neovim
    #   - Installing Python 3 NeoVim plugin
    - - nvim -c 'PlugClean!' -c 'PlugInstall' -c 'PlugUpdate' -c 'q' -c 'q'
      - Installing vim plugins
