# See https://gitlab.com/flyingchipmunk/dotbot-yum
- defaults:
    yum:
      options: "-q -y --nogpgcheck"
      sudo: True
      stdout: False
      stderr: True

- yum:
  - ca-certificates
  - wget
  - glibc-locale-source # Require for localedef used in bash config

- yum:
  - >-
    gcc findutils
    zlib-devel readline-devel libffi-devel
    bzip2 bzip2-devel sqlite sqlite-devel xz xz-devel

- yum:
  - python3-pip # Require for alias_tips

- yum:
  - ccze
