# See https://gitlab.com/flyingchipmunk/dotbot-yum
- defaults:
    yum:
      options: "-q -y --nogpgcheck"
      sudo: True
      stdout: False
      stderr: True

# - yum:
#     dev-yumgroup:
#       options: '-q -y --disablerepo=* --enablerepo=mainline --enablerepo=mainline-extra'
#       group: True

- yum:
  - epel-release
  - ca-certificates
  - wget

- yum:
  - >-
    gcc findutils
    zlib-devel readline-devel libffi-devel
    bzip2 bzip2-devel sqlite sqlite-devel xz xz-devel

- yum:
  - python3-pip # Require for alias_tips

- yum:
  - ccze
