# See https://gitlab.com/flyingchipmunk/dotbot-yum
- defaults:
    yum:
      options: "-q -y --nogpgcheck"
      sudo: True
      stdout: False
      stderr: True

# - yum:
#     dev-yumgroup:
#       options: '-q -y --disablerepo=* --enablerepo=mainline --enablerepo=mainline-extra'
#       group: True

- yum:
  - epel-release
