- defaults:
    link:
      create: true
      relink: true
      force: true
- clean:
    - ~/.config/plugins
    - ~/.config/zsh
- link:
    ~/.zshenv: shells/zsh/zshenv
    ~/.config/zsh/.zshenv: shells/zsh/config/zsh/zshenv
    ~/.config/zsh/.zprofile: shells/zsh/config/zsh/zprofile
    ~/.config/zsh/.zshrc: shells/zsh/config/zsh/zshrc
    ~/.config/zsh/.zlogin: shells/zsh/config/zsh/zlogin
    ~/.config/zsh/.zlogout: shells/zsh/config/zsh/zlogout
    ~/.config/zsh/aliases/aliases.zsh: shells/zsh/config/zsh/aliases/aliases.zsh
    ~/.config/zsh/aliases/apg.zsh: shells/zsh/config/zsh/aliases/apg.zsh
    # ~/.config/zsh/aliases/fzf_commands.zsh: shells/zsh/config/zsh/aliases/fzf_commands.zsh
    ~/.config/zsh/aliases/git.zsh: shells/zsh/config/zsh/aliases/git.zsh
    # ~/.config/zsh/aliases/global.aliases.zsh: shells/zsh/config/zsh/aliases/global.aliases.zsh
    ~/.config/zsh/aliases/mancolors.zsh: shells/zsh/config/zsh/aliases/mancolors.zsh
    ~/.config/zsh/aliases/ssh.zsh: shells/zsh/config/zsh/aliases/ssh.zsh
    ~/.config/zsh/aliases/todo-txt.zsh: shells/zsh/config/zsh/aliases/todo-txt.zsh
    ~/.config/zsh/completions/_c: shells/zsh/config/zsh/completions/_c
    ~/.config/zsh/completions/_gibo: shells/zsh/config/zsh/completions/_gibo
    ~/.config/zsh/completions/_padrino: shells/zsh/config/zsh/completions/_padrino
    ~/.config/zsh/completions/_sheet: shells/zsh/config/zsh/completions/_sheet
    ~/.config/zsh/functions/c: shells/zsh/config/zsh/functions/c
    ~/.config/zsh/functions/em: shells/zsh/config/zsh/functions/em
    ~/.config/zsh/functions/dotfiles-update: shells/zsh/config/zsh/functions/dotfiles-update
    ~/.config/zsh/functions/fn: shells/zsh/config/zsh/functions/fn
    ~/.config/zsh/functions/g: shells/zsh/config/zsh/functions/g
    ~/.config/zsh/functions/git-escape-magic: shells/zsh/config/zsh/functions/git-escape-magic
    ~/.config/zsh/functions/killport: shells/zsh/config/zsh/functions/killport
    ~/.config/zsh/functions/pmodload: shells/zsh/config/zsh/functions/pmodload
    ~/.config/zsh/functions/prepend: shells/zsh/config/zsh/functions/prepend
    ~/.config/zsh/functions/pzt_extract_alias: shells/zsh/config/zsh/functions/pzt_extract_alias
    ~/.config/zsh/functions/pzt_update_externals: shells/zsh/config/zsh/functions/pzt_update_externals
    ~/.config/zsh/functions/pzt_whatsnext: shells/zsh/config/zsh/functions/pzt_whatsnext
    ~/.config/zsh/functions/spectrum: shells/zsh/config/zsh/functions/spectrum
    ~/.config/zsh/functions/take: shells/zsh/config/zsh/functions/take
    ~/.config/zsh/settings/abbreviations.zsh: shells/zsh/config/zsh/settings/abbreviations.zsh
    # ~/.config/zsh/settings/bindkeys.zsh: shells/zsh/config/zsh/settings/bindkeys.zsh
    ~/.config/zsh/settings/externals: shells/zsh/config/zsh/settings/externals
    # ~/.config/zsh/settings/fasd.zsh: shells/zsh/config/zsh/settings/fasd.zsh
    ~/.config/zsh/settings/zshsetopts.zsh: shells/zsh/config/zsh/settings/zshsetopts.zsh
    # ~/.config/zsh/themes/prompt_anishathalye_setup: shells/zsh/config/zsh/themes/prompt_anishathalye_setup
    # ~/.config/zsh/themes/prompt_ayk_setup: shells/zsh/config/zsh/themes/prompt_ayk_setup
    # ~/.config/zsh/themes/prompt_pbr_setup: shells/zsh/config/zsh/themes/prompt_pbr_setup
    # ~/.config/zsh/themes/prompt_squeak_setup: shells/zsh/config/zsh/themes/prompt_squeak_setup
    ~/.config/zsh/themes/prompt_pure_setup: shells/zsh/config/zsh/themes/prompt_pure_setup
    ~/.config/zsh/zle/fancy-ctrl-z.zsh: shells/zsh/config/zsh/zle/fancy-ctrl-z.zsh
    ~/.config/zsh/zle/last-command.zsh: shells/zsh/config/zsh/zle/last-command.zsh
    ~/.config/zsh/zle/select-history.zsh: shells/zsh/config/zsh/zle/select-history.zsh
    ~/.config/zsh/zle/zleiab.zsh: shells/zsh/config/zsh/zle/zleiab.zsh
    ~/.config/plugins/dircolors.extra: shells/plugins/dircolors.extra
    ~/.config/plugins/dircolors-solarized/dircolors.256dark: shells/plugins/dircolors-solarized/dircolors.256dark
