#!/bin/bash -i

set -e

# Do not continue until umask is fixed
if [ "$(umask)" = "0000" ]; then
  echo "WSL umask was not fixed, cannot continue!"
  exit 1
fi

BASE_CONFIG="base"
CONFIG_SUFFIX=".yaml"

META_DIR="meta"
CONFIG_DIR="configs"
PROFILES_DIR="profiles"

DOTBOT_DIR="dotbot"
DOTBOT_BIN="bin/dotbot"

BASE_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

PLUGIN_DIR="dotbot-plugins"
PROFILE_PLUGIN_DIR="${PLUGIN_DIR}/$1"

if [[ "$1" = "macos" ]]; then
  # Install Xcode command line tools first before use git command
  xcode-select --install || echo Xcode command line tools installed.
fi

cd "${BASE_DIR}"
git submodule update --init --checkout --recursive --force

# HACK to make dotbot-brew work since Linuxbrew does not add PATH automatically.
if ! which brew; then
  echo "Loading Homebrew..."
  export PATH="/home/linuxbrew/.linuxbrew/bin:$PATH"

  ############
  # Homebrew
  ############
  if [ -f /opt/homebrew/bin/brew ]; then
    eval "$(/opt/homebrew/bin/brew shellenv)"
  fi
fi

# Write update-dotfiles to use later
UPDATE_FILE=~/update-dotfiles.sh
if [ ! -f ${UPDATE_FILE} ]; then
  echo 'cd ~/ && curl -O https://raw.githubusercontent.com/nobitagamer/dotfiles/master/.dots && . ./.dots' > ${UPDATE_FILE}
  chmod +x ${UPDATE_FILE}
fi

while IFS= read -r config; do
    CONFIGS+=" ${config}"
done < "${META_DIR}/${PROFILES_DIR}/$1"

shift

# Force use Python2 to avoid `SyntaxWarning for 'is' with literals` on Python 3.8.5 from MacOS Catalina
# See https://adamj.eu/tech/2020/01/21/why-does-python-3-8-syntaxwarning-for-is-literal/
which python3 >/dev/null 2>&1 && alias python=python3
which python2 >/dev/null 2>&1 && alias python=python2
which python2.7 >/dev/null 2>&1 && alias python=python2.7
python --version

python "${BASE_DIR}/${META_DIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" \
    -d "${BASE_DIR}"                                  \
    --plugin-dir "${META_DIR}/${PLUGIN_DIR}"          \
    --plugin-dir "${META_DIR}/${PROFILE_PLUGIN_DIR}"  \
    --plugin-dir "${META_DIR}/dotbot-brew"            \
    --plugin-dir "${META_DIR}/dotbot-pip"             \
    --plugin-dir "${META_DIR}/dotbot-yum"             \
    -c "${META_DIR}/${BASE_CONFIG}${CONFIG_SUFFIX}"

    # --plugin-dir "${META_DIR}/dotbot-brewfile"        \

for config in ${CONFIGS} "${@}"; do
    echo -e "\nConfiguring $config..."

    python "${BASE_DIR}/${META_DIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" \
        -d "${BASE_DIR}"                                  \
        --plugin-dir "${META_DIR}/${PLUGIN_DIR}"          \
        --plugin-dir "${META_DIR}/${PROFILE_PLUGIN_DIR}"  \
        --plugin-dir "${META_DIR}/dotbot-brew"            \
        --plugin-dir "${META_DIR}/dotbot-pip"             \
        --plugin-dir "${META_DIR}/dotbot-yum"             \
        -c "${META_DIR}/${CONFIG_DIR}/${config}${CONFIG_SUFFIX}"

        # --plugin-dir "${META_DIR}/dotbot-brewfile"        \

done
