#!/bin/bash -i

set -e

# Do not continue until umask is fixed
if [ "$(umask)" = "0000" ]; then
  echo "WSL umask was not fixed, cannot continue!"
  exit 1
fi

BASE_CONFIG="base"
CONFIG_SUFFIX=".yaml"

META_DIR="meta"
CONFIG_DIR="configs"

DOTBOT_DIR="dotbot"
DOTBOT_BIN="bin/dotbot"

BASE_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

PLUGIN_DIR="dotbot-plugins"

cd "${BASE_DIR}"
# !NOTE: MUST use specific version of dotbot recorded in repo.
git submodule update --checkout --recursive --force

# HACK to make dotbot-brew work since Linuxbrew does not add PATH automatically.
if [[ `which brew` = "" ]]; then
  export PATH="/home/linuxbrew/.linuxbrew/bin:$PATH"
fi

"${BASE_DIR}/${META_DIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" \
    -d "${BASE_DIR}"                                  \
    --plugin-dir "${META_DIR}/${PLUGIN_DIR}"          \
    --plugin-dir "${META_DIR}/dotbot-brew"            \
    --plugin-dir "${META_DIR}/dotbot-brewfile"        \
    --plugin-dir "${META_DIR}/dotbot-pip"             \
    --plugin-dir "${META_DIR}/dotbot-yum"             \
    -c "${META_DIR}/${BASE_CONFIG}${CONFIG_SUFFIX}"

for config in ${@}; do
    "${BASE_DIR}/${META_DIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" \
        -d "${BASE_DIR}"                                  \
        --plugin-dir "${META_DIR}/${PLUGIN_DIR}"          \
        --plugin-dir "${META_DIR}/dotbot-brew"            \
        --plugin-dir "${META_DIR}/dotbot-brewfile"        \
        --plugin-dir "${META_DIR}/dotbot-pip"             \
        --plugin-dir "${META_DIR}/dotbot-yum"             \
        -c "${META_DIR}/${CONFIG_DIR}/${config}${CONFIG_SUFFIX}"
done
