#!/bin/bash -i

set -e

# Do not continue until umask is fixed
if [ "$(umask)" = "0000" ]; then
  echo "WSL umask was not fixed, cannot continue!"
  exit 1
fi

BASE_CONFIG="base"
CONFIG_SUFFIX=".yaml"

META_DIR="meta"
CONFIG_DIR="configs"
PROFILES_DIR="profiles"

DOTBOT_DIR="dotbot"
DOTBOT_BIN="bin/dotbot"

BASE_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

PLUGIN_DIR="dotbot-plugins"
PROFILE_PLUGIN_DIR="${PLUGIN_DIR}/$1"

cd "${BASE_DIR}"
git submodule update --init --recursive --remote

# HACK to make dotbot-brew work since Linuxbrew does not add PATH automatically.
if [[ $(which brew) = "" ]]; then
  export PATH="/home/linuxbrew/.linuxbrew/bin:$PATH"
fi

# Write update-dotfiles to use later
UPDATE_FILE=~/update-dotfiles.sh
if [ ! -f ${UPDATE_FILE} ]; then
  echo 'cd ~/ && curl -O https://raw.githubusercontent.com/nobitagamer/dotfiles/master/.dots && . ./.dots' > ${UPDATE_FILE}
  chmod +x ${UPDATE_FILE}
fi

while IFS= read -r config; do
    CONFIGS+=" ${config}"
done < "${META_DIR}/${PROFILES_DIR}/$1"

shift

"${BASE_DIR}/${META_DIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" \
    -d "${BASE_DIR}"                                  \
    --plugin-dir "${META_DIR}/${PLUGIN_DIR}"          \
    --plugin-dir "${META_DIR}/${PROFILE_PLUGIN_DIR}"  \
    --plugin-dir "${META_DIR}/dotbot-brew"            \
    --plugin-dir "${META_DIR}/dotbot-pip"             \
    --plugin-dir "${META_DIR}/dotbot-yum"             \
    -c "${META_DIR}/${BASE_CONFIG}${CONFIG_SUFFIX}"

    # --plugin-dir "${META_DIR}/dotbot-brewfile"        \

for config in ${CONFIGS} "${@}"; do
    echo -e "\nConfiguring $config..."

    "${BASE_DIR}/${META_DIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" \
        -d "${BASE_DIR}"                                  \
        --plugin-dir "${META_DIR}/${PLUGIN_DIR}"          \
        --plugin-dir "${META_DIR}/${PROFILE_PLUGIN_DIR}"  \
        --plugin-dir "${META_DIR}/dotbot-brew"            \
        --plugin-dir "${META_DIR}/dotbot-pip"             \
        --plugin-dir "${META_DIR}/dotbot-yum"             \
        -c "${META_DIR}/${CONFIG_DIR}/${config}${CONFIG_SUFFIX}"

        # --plugin-dir "${META_DIR}/dotbot-brewfile"        \

done
