[settings]
# plugins can read the versions files used by other version managers (if enabled by the plugin)
# for example, .nvmrc in the case of node's nvm
legacy_version_file = true                     # enabled by default (unlike asdf)
#legacy_version_file_disable_tools = ['python'] # disable for specific tools

asdf_compat = true # set to true to ensure .tool-versions will be compatible with asdf, see `MISE_ASDF_COMPAT`

env_file = '.envrc' # load env vars from a dotenv file, see `MISE_ENV_FILE`
idiomatic_version_file_enable_tools = ["terraform", "ruby", "node", "python"]

# !NOTE: precompiled ruby will be the default in 2026.8.0
[settings.ruby]
compile = false

[tools]
node = "22.22.1"
ruby = "3.4.9"
websocat = "1.14.1"
"npm:@google/gemini-cli" = "0.1.5"
