# ~/.zshenv should only be a one-liner that sources this file
# echo ". ~/.config/zsh/.zshenv" > ~/.zshenv
#!/usr/bin/env zsh

# XDG stuff
XDG_CACHE_HOME=$HOME/.cache
XDG_CONFIG_HOME=$HOME/.config
XDG_DATA_HOME=$HOME/.local/share
[ -d $HOME/.xdg ] && XDG_RUNTIME_DIR=$HOME/.xdg

GNUPGHOME=$XDG_CONFIG_HOME/gnupg

ZDOTDIR=${XDG_CONFIG_HOME:=$HOME/.config}/zsh

export XDG_CACHE_HOME XDG_CONFIG_HOME XDG_DATA_HOME XDG_RUNTIME_DIR GNUPGHOME ZDOTDIR

source $ZDOTDIR/.zshenv
