#!/bin/sh

# Load and configure smartcd
source ~/.smartcd/lib/core/arrays
source ~/.smartcd/lib/core/varstash
source ~/.smartcd/lib/core/smartcd

# smartcd setup chpwd-hook
smartcd setup cd
smartcd setup pushd
smartcd setup popd

# support "autocd"
# smartcd setup prompt-hook # !Cause bash error: trap: __bp_install: invalid signal specification
# smartcd setup exit-hook

smartcd setup completion
# automatically add stash commands to your enter scripts
VARSTASH_AUTOCONFIGURE=1

# edit the smartcd config after it is automatically configured
VARSTASH_AUTOEDIT=1

# SMARTCD_NO_INODE=1
# SMARTCD_AUTOMIGRATE=1
# SMARTCD_LEGACY=1
# SMARTCD_QUIET=1
# VARSTASH_QUIET=1
